### ISSUE TITLE
Benchmark interface

### ISSUE THREAD

**Issue by marcelja** [hyrise/index_selection_evaluation#28]
The Benchmark class has a lot of parameters. This could be made a bit smaller, e.g. by creating a dictionary for values that are only used to store in the csv

**Comment by Bensk1** [comment]
Any news on that?

**Comment by marcelja** [comment]
No, but I can implement this tomorrow

**Comment by Bensk1** [comment]
You certainly don't have to, I just wanted to ask to see if we should close that or if there is any code for that.

**Comment by marcelja** [comment]
Ok, we can close this.
