### ISSUE TITLE
Where is CoPhy code

### ISSUE THREAD

**Issue by hnjylwb** [hyrise/index_selection_evaluation#43]
I didn't find the implementation of CoPhy in the code. Could you please add the CoPhy code?

**Comment by klauck** [comment]
We implemented CoPhy using AMPL. (The code is already in the repo.)

Programming model:
[https://github.com/hyrise/index_selection_evaluation/blob/refactoring/benchmark_results/cophy_ampl_model.mod]()

Input data for TPC-H:
[https://github.com/hyrise/index_selection_evaluation/blob/refactoring/benchmark_results/tpch_wo_2_17_20/cophy_ampl_data_tpch_3_1.txt]()

**Comment by hnjylwb** [comment]
Oh I see, thanks!
