### ISSUE TITLE
Question with b_to_mb and mb_to_b

### ISSUE THREAD

**Issue by earthwuyang** [hyrise/index_selection_evaluation#46]
Hello, I found that b_to_mb and mb_to_b in selection/utils.py are multiplied or divided by 1000. But I remember people often use 1MB=2**20 B instead of 10**6 which is the case of conversion of second and miliseconds. Will this matter?

**Comment by earthwuyang** [comment]
As for the format, it's 2^20 and 10^6

**Comment by Bensk1** [comment]
I cannot think of any case where this should matter. Do you have any specific conversion problem or use case in mind?

We did not see any advantage of the 2^20 definition and this would actually be mebibyte, which are abbreviated as `MiB` instead of `MB`.

**Comment by earthwuyang** [comment]
Thank you! I got it. You are right. I met the problem because MB is differently used in my country. Sorry for bothering!
